### PR TITLE
Add maven deploy plugin for camel web service pipeline

### PR DESCRIPTION
**Pull request by rlratcliffe**
The profile is used/added so that when REG_HOST isn't provided (during local development, for example) the environment variable doesn't need to be provided by the developer

### CODE REVIEW

**Comment by jam01** [comment]
:thinking:

**Comment by rlratcliffe** [comment]
if we do decide to use the profile, I'm of course open to the changing the profile id or even adding a comment for clarity about why it's there

**Comment by jam01** [comment]
Let's change the maven deploy plugin for this property
```
        <maven.deploy.skip>true</maven.deploy.skip>
```

Windows builds still failing?

**Comment by rlratcliffe** [comment]
> Let's change the maven deploy plugin for this property
> 
> ```
>         <maven.deploy.skip>true</maven.deploy.skip>
> ```
> 
> Windows builds still failing?

What should it change to? This is being changed here I believe: https://github.com/MS3Inc/camel-archetypes/pull/26/files#diff-aca6fb8b598ee90ea4549b1086094e0fe5de96296e7f11c1b7288c4d396873b3R226

**Comment by jam01** [comment]
instead of including the plugin, just set that property

**Comment by rlratcliffe** [comment]
is there a reason we decided not to use jib or fabric8's deploy plugin? can I try out one of those? @jam01 @rmccright-ms3

**Comment by jam01** [comment]
I think Spotify's was just the first we found. I used jib in another project without issues

**Comment by jam01** [comment]
I'm not sure if the plugin is being continued but I know in general fabric8 as an org does not exist anymore.

**Comment by rlratcliffe** [comment]
yeah. there's no indication in their repo that it's not supported anymore though, unlike spotify's plugin which spotify is no longer updating.

I didn't go with jib because it doesn't seem to support dockerfiles, it's all xml configuration instead. :thinking: 

this windows error is different than the last one though, and does work with `mvn clean install` on the windows machine I tried it on.

**Comment by rlratcliffe** [comment]
did a lot of tests on windows today and on a private personal repo with github actions. here's the summary of what I've figured out so far:

this issue with windows seems to be primarily related to github actions.

with windows with docker that uses windows containers
- github actions supports
- jib doesn't support
- fabric8 works, if switching dockerfile to use something like winamd64/openjdk:11

with windows with docker that uses linux containers 
- github actions doesn't support
- jib supports
- fabric8 works, if using dockerfile with the previously used adoptopenjdk/openjdk11:alpine-jre

next ideas for resolving:
- not going back to trying spotify, because it's deprecated
- not going to continue trying with fabric8 because it's also deprecated, and managing two Dockerfiles or overriding just the FROMs (via cli?) are not good solutions anyway imo.
- jib has benefits of seemingly creating a smaller image that is still layered, without a dockerfile. but some people may want the customization of a dockerfile (they could use a different plugin though if they need). could attempt to use bash if statement to conditionally skip jib build in the test if windows is detected. I don't think the test should be removed completely from windows.
- look into eclipse jkube more

**Comment by rlratcliffe** [comment]
was having trouble configuring jkube, so switched back to fabric8 just to make sure I could get the two different configs for the dockerfile working correctly. now that it is, moving back to jkube.

**Comment by rlratcliffe** [comment]
still need to:

- finish testing deploy using the pipelines
- figure out if that layer I removed in the dockerfile is really needed or how to allow it to stay without it erroring out. adding `RUN true` after the second copy works in linux, but not in windows.

**Comment by rlratcliffe** [comment]
switching to using kaniko, so abandoning this.

**Pull request closed without merging**
